/**
 * Build information
 * Auto-generated by scripts/generate-build-info.mjs — do not edit manually.
 */

export type BuildInfo = { commitHash: string; commitShort: string; buildTime: string; buildYear: number }

export const BUILD_INFO: BuildInfo = {
  commitHash: '2db07414fffde3b0c40d9f45c5b08cc5ee9e5629',
  commitShort: '2db0741',
  buildTime: '2026-04-21T17:21:35.096Z',
  buildYear: 2026,
}
