/**
 * Build information
 * Auto-generated by scripts/generate-build-info.mjs — do not edit manually.
 */

export type BuildInfo = { commitHash: string; commitShort: string; buildTime: string; buildYear: number }

export const BUILD_INFO: BuildInfo = {
  commitHash: '94078c2b313310bde98f3fd29e947d78122d199d',
  commitShort: '94078c2',
  buildTime: '2026-04-21T18:06:50.842Z',
  buildYear: 2026,
}
