name: Wait for Pantheon build and clear cache

on:
  push:
    branches: [main]

jobs:
  wait-and-flush:
    runs-on: ubuntu-latest
    steps:
      - uses: jazzsequence/pantheon-wait-for-build@main
        with:
          pantheon-machine-token: ${{ secrets.TERMINUS_TOKEN }}
          site-name: devrel-wait-for-build
          clear-cache: 'true'
